packages:
  - apps/api
  - apps/web
  - packages/trpc
  - packages/utils

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.28.0
  '@trivago/prettier-plugin-sort-imports': ^5.2.2
  '@typescript-eslint/eslint-plugin': ^8.34.0
  '@typescript-eslint/parser': ^8.34.0
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.4.1
  globals: ^16.2.0
  prettier: ^3.7.4
  typescript: ^5.8.3

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
