/**
 * @school/shared - 도메인 공유 패키지
 *
 * 서버/클라이언트가 공유하는 도메인 상수, 타입, Zod 스키마 정의
 */

// 도메인 상수 + 타입
export {
    ROLE,
    JOIN_REQUEST_STATUS,
    GENDER,
    PRESENT_MARKS,
    ORGANIZATION_TYPE,
    MAX_GRADUATION_AGE,
    getMaxGraduationAge,
    GROUP_TYPE,
} from './constants.js';
export type {
    AccountInfo,
    OrganizationInfo,
    ChurchInfo,
    Role,
    JoinRequestStatus,
    Gender,
    OrganizationType,
    GroupType,
} from './constants.js';

// 도메인 인증 상태
export type { AuthState } from './auth.js';

// Zod 스키마 (Input)
export {
    idSchema,
    pageSchema,
    searchOptionSchema,
    searchWordSchema,
    loginInputSchema,
    checkIdInputSchema,
    signupInputSchema,
    resetPasswordInputSchema,
    restoreAccountInputSchema,
    changePasswordInputSchema,
    updateProfileInputSchema,
    deleteAccountInputSchema,
    getGroupInputSchema,
    listGroupsInputSchema,
    createGroupInputSchema,
    updateGroupInputSchema,
    deleteGroupInputSchema,
    bulkDeleteGroupsInputSchema,
    getGroupAttendanceInputSchema,
    addStudentToGroupInputSchema,
    removeStudentFromGroupInputSchema,
    bulkAddStudentsToGroupInputSchema,
    bulkRemoveStudentsFromGroupInputSchema,
    listStudentsInputSchema,
    getStudentInputSchema,
    createStudentInputSchema,
    updateStudentInputSchema,
    deleteStudentInputSchema,
    bulkDeleteStudentsInputSchema,
    restoreStudentsInputSchema,
    graduateStudentsInputSchema,
    cancelGraduationInputSchema,
    bulkCreateStudentsInputSchema,
    bulkRegisterStudentsInputSchema,
    bulkCancelRegistrationInputSchema,
    feastDayListInputSchema,
    updateAttendanceInputSchema,
    getCalendarInputSchema,
    getDayDetailInputSchema,
    getExcellentStudentsInputSchema,
    statisticsInputSchema,
    topStatisticsInputSchema,
    getHolydaysInputSchema,
    getSeasonInputSchema,
    createChurchInputSchema,
    searchChurchesInputSchema,
    listOrganizationsInputSchema,
    createOrganizationInputSchema,
    requestJoinInputSchema,
    approveJoinInputSchema,
    rejectJoinInputSchema,
    transferAdminInputSchema,
} from './schemas/index.js';

// 입력 타입 (Input)
export type {
    LoginInput,
    CheckIdInput,
    SignupInput,
    ResetPasswordInput,
    RestoreAccountInput,
    ChangePasswordInput,
    UpdateProfileInput,
    DeleteAccountInput,
    GetGroupInput,
    ListGroupsInput,
    CreateGroupInput,
    UpdateGroupInput,
    DeleteGroupInput,
    BulkDeleteGroupsInput,
    GetGroupAttendanceInput,
    AddStudentToGroupInput,
    RemoveStudentFromGroupInput,
    BulkAddStudentsToGroupInput,
    BulkRemoveStudentsFromGroupInput,
    ListStudentsInput,
    GetStudentInput,
    CreateStudentInput,
    UpdateStudentInput,
    DeleteStudentInput,
    BulkDeleteStudentsInput,
    RestoreStudentsInput,
    GraduateStudentsInput,
    CancelGraduationInput,
    BulkCreateStudentsInput,
    BulkRegisterStudentsInput,
    BulkCancelRegistrationInput,
    FeastDayListInput,
    AttendanceData,
    UpdateAttendanceInput,
    GetCalendarInput,
    GetDayDetailInput,
    GetExcellentStudentsInput,
    StatisticsInput,
    TopStatisticsInput,
    GetHolydaysInput,
    GetSeasonInput,
    CreateChurchInput,
    SearchChurchesInput,
    ListOrganizationsInput,
    CreateOrganizationInput,
    RequestJoinInput,
    ApproveJoinInput,
    RejectJoinInput,
    TransferAdminInput,
} from './schemas/index.js';

// 출력 타입 (Output)
export type {
    // Auth
    LoginOutput,
    CheckIdOutput,
    SignupOutput,
    ResetPasswordOutput,
    RestoreAccountOutput,
    RefreshOutput,
    LogoutOutput,
    // Account
    GetAccountOutput,
    AgreePrivacyOutput,
    GetAccountCountOutput,
    ChangePasswordOutput,
    UpdateProfileOutput,
    DeleteAccountOutput,
    // Group
    GroupOutput,
    CreateGroupOutput,
    GetGroupOutput,
    ListGroupsOutput,
    AttendanceItem,
    GetGroupAttendanceOutput,
    BulkDeleteGroupsOutput,
    // Student
    StudentGroupItem,
    StudentBase,
    StudentWithGroup,
    ListStudentsOutput,
    GetStudentOutput,
    CreateStudentOutput,
    UpdateStudentOutput,
    DeleteStudentOutput,
    PromoteStudentsOutput,
    BulkCreateStudentsOutput,
    BulkDeleteStudentsOutput,
    RestoreStudentsOutput,
    GraduatedStudent,
    SkippedStudent,
    GraduateStudentsOutput,
    CancelGraduationOutput,
    FeastDayStudentItem,
    FeastDayListOutput,
    RegistrationSummary,
    BulkRegisterStudentsOutput,
    BulkCancelRegistrationOutput,
    // Attendance
    UpdateAttendanceOutput,
    CalendarDayAttendance,
    CalendarDay,
    GetCalendarOutput,
    StudentAttendanceDetail,
    GetDayDetailOutput,
    HasAttendanceOutput,
    // Statistics
    ExcellentStudent,
    GetExcellentStudentsOutput,
    AttendanceRateOutput,
    GenderDistributionOutput,
    TopGroupItem,
    TopGroupsOutput,
    TopOverallStudentItem,
    TopOverallOutput,
    GroupStatisticsItem,
    GroupStatisticsOutput,
    // Liturgical
    Holyday,
    GetHolydaysOutput,
    GetSeasonOutput,
    // Parish
    ParishItem,
    ListParishesOutput,
    // Church
    CreateChurchOutput,
    SearchChurchItem,
    SearchChurchesOutput,
    // Organization
    OrganizationItem,
    ListOrganizationsOutput,
    CreateOrganizationOutput,
    RequestJoinOutput,
    PendingRequestItem,
    PendingRequestsOutput,
    MemberItem,
    MembersOutput,
    TransferAdminOutput,
} from './schemas/index.js';
